apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureapp-dev

resources:
- ../../base

namePrefix: dev-

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: api
              resources:
                requests:
                  cpu: "50m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=debug
  - WORKERS=1
  name: secureapp-config
images:
- digest: sha256:f236c1a0b54aec236e1ad25eafa2fa0cea649932fc8e31de9f866dfa293101bb
  name: ahmed-magdi2712/DevSecOps-Usecase
  newName: ghcr.io/ahmed-magdi2712/devsecops-usecase
